let menu = document.querySelector('.menu')
let bg_menu = document.querySelector('.bg_menu')
let bgl = document.querySelector('section')
let logo = document.querySelector('.cbçlh-content-logo a img')
let darkt = document.querySelector('.darkt span s')
let darkt_check = document.querySelector('.darkt input')